modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/tterrag1098/DummyPlayers/issues"
license = "MPLv2"

[[mods]]
modId="dummyplayers"
version="${file.jarVersion}"
displayName="DummyPlayers"
authors="tterrag" #optional

[[dependencies.dummyplayers]] 
    modId="forge"
    mandatory=true 
    versionRange="[40.1.84,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dummyplayers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"