modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/tterrag1098/DummyPlayers/issues"
license = "MPLv2"

[[mods]]
modId="dummyplayers"
version="${file.jarVersion}"
displayName="DummyPlayers"
authors="tterrag" #optional

[[dependencies.dummyplayers]] 
    modId="forge"
    mandatory=true 
    versionRange="[47.1.79,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dummyplayers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"